♻️ Refactor dockerfile and upgrade next #1128

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,104 +1,77 @@
-ARG ARG_DYNATRACE_IMAGE='node:lts-alpine'
+ARG ARG_DYNATRACE_IMAGE='node:16-alpine'
+
 FROM ${ARG_DYNATRACE_IMAGE} AS dynatrace
 
-FROM node:lts-alpine AS builder
+FROM node:16-alpine AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-RUN npm install -g pnpm@^7.2.1
+COPY package.json pnpm-lock.yaml ./
+COPY web/package.json web/pnpm-lock.yaml web/
 
-WORKDIR /opt/app
+RUN \
+  if [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm m i --frozen-lockfile;\
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Should consider using pnpm fetch
-COPY ./package.json ./
-COPY ./pnpm-lock.yaml ./
-COPY ./tsconfig.base.json ./
-COPY ./satellitesConfig.js ./
-COPY ./FeatureFlags.js ./
-COPY ./pnpm-workspace.yaml ./
-COPY ./.npmrc ./
-COPY ./web ./web
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY --from=deps /app/web/node_modules ./web/node_modules
+COPY . .
 
-# Replace workspace:* with the actual versions | Load css from public folder atm
-# RUN version=$(jq --raw-output .version ./legacy/css/package.json); \
-#  jq --arg legacy_css "$version" '.dependencies["@equinor/energyvision-legacy-css"] = $legacy_css' \
-#  ./web/package.json | sponge ./web/package.json
-
-ARG ARG_SANITY_PROJECT_ID
 ARG ARG_SANITY_DATASET
-ARG ARG_ALGOLIA_APP_ID
-ARG ARG_ALGOLIA_SEARCH_API_KEY
-
-ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${ARG_SANITY_PROJECT_ID}
 ENV NEXT_PUBLIC_SANITY_DATASET ${ARG_SANITY_DATASET}
-ENV NEXT_PUBLIC_ALGOLIA_APP_ID ${ARG_ALGOLIA_APP_ID}
-ENV NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY ${ARG_ALGOLIA_SEARCH_API_KEY}
+ARG ARG_SANITY_PROJECT_ID
+ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${ARG_SANITY_PROJECT_ID}
 
-#RUN pnpm install --recursive --frozen-lockfile
-RUN pnpm web install --frozen-lockfile
-RUN pnpm web build
+ENV NEXT_TELEMETRY_DISABLED 1
 
-FROM node:lts-alpine as runner
+RUN cd web && yarn build
 
-RUN npm install -g pnpm@^7.2.1
 
-WORKDIR /opt/app
+# Production image, copy all the files and run next
+FROM node:16-alpine AS runner
+WORKDIR /app
 
 ENV NODE_ENV production
-ENV PORT 3000
-ENV USER nextjs
-ENV UID 12345
-ENV GID 23456
-
-RUN addgroup -S "$USER" && \
-  adduser -S \
-  --disabled-password \
-  --gecos "" \
-  --home "/opt/app" \
-  --ingroup "$USER" \
-  --no-create-home \
-  --uid "$UID" \
-  "$USER"
-
-COPY --from=builder /opt/app/web/.next ./web/.next
-COPY --from=builder /opt/app/web/next.config.mjs ./web
-COPY --from=builder /opt/app/web/securityHeaders.mjs ./web
-COPY --from=builder /opt/app/web/package.json ./web
-COPY --from=builder /opt/app/web/node_modules ./web/node_modules
-COPY --from=builder /opt/app/web/pnpm-lock.yaml ./web
-COPY --from=builder /opt/app/web/languages.js ./web
-COPY --from=builder /opt/app/pnpm-lock.yaml ./
-COPY --from=builder /opt/app/web/public ./web/public
-COPY --from=builder /opt/app/package.json ./
-COPY --from=builder /opt/app/satellitesConfig.js ./
-COPY --from=builder /opt/app/pnpm-workspace.yaml ./
-COPY --from=builder /opt/app/.npmrc ./
-
-RUN chown -R "$USER":"$USER" .
-USER "$UID"
-
-ARG ARG_SANITY_PROJECT_ID
-ARG ARG_SANITY_DATASET
-ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${ARG_SANITY_PROJECT_ID}
-ENV NEXT_PUBLIC_SANITY_DATASET ${ARG_SANITY_DATASET}
-
-ARG ARG_SANITY_API_TOKEN
-ARG ARG_SANITY_PREVIEW_SECRET
-
-ENV SANITY_API_TOKEN ${ARG_SANITY_API_TOKEN}
-ENV SANITY_PREVIEW_SECRET ${ARG_SANITY_PREVIEW_SECRET}
-
-ARG ARG_ALGOLIA_APP_ID
-ARG ARG_ALGOLIA_SEARCH_API_KEY
-ARG ARG_ALGOLIA_SEARCH_API_SERVER_KEY
-ENV NEXT_PUBLIC_ALGOLIA_APP_ID ${ARG_ALGOLIA_APP_ID}
-ENV NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY ${ARG_ALGOLIA_SEARCH_API_KEY}
-ENV ALGOLIA_SEARCH_API_SERVER_KEY ${ARG_ALGOLIA_SEARCH_API_SERVER_KEY}
 
 ARG ARG_ENV
 ENV ENV ${ARG_ENV}
+ARG ARG_SANITY_DATASET
+ENV NEXT_PUBLIC_SANITY_DATASET ${ARG_SANITY_DATASET}
+ARG ARG_SANITY_PROJECT_ID
+ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${ARG_SANITY_PROJECT_ID}
+ARG ARG_ALGOLIA_APP_ID
+ENV NEXT_PUBLIC_ALGOLIA_APP_ID ${ARG_ALGOLIA_APP_ID}
+ARG ARG_ALGOLIA_SEARCH_API_KEY
+ENV NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY ${ARG_ALGOLIA_SEARCH_API_KEY}
+ARG ARG_ALGOLIA_SEARCH_API_SERVER_KEY
+ENV ALGOLIA_SEARCH_API_SERVER_KEY ${ARG_ALGOLIA_SEARCH_API_SERVER_KEY}
 
+ENV PORT 3000
+ENV USER nextjs
+ENV UID 12345
+# https://nextjs.org/telemetry
+ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup -S "$USER"
+RUN adduser -S --uid "$UID" "$USER"
+
+COPY --from=builder /app/web/public ./public
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown="$USER":"$USER" /app/web/.next/standalone .
+COPY --from=builder --chown="$USER":"$USER" /app/web/.next/static ./.next/static
+
+USER "$UID"
+
+# Copy dynatrace or "empty"
 COPY --from=dynatrace / /
 ENV LD_PRELOAD /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so
 ENV DT_TAGS=EQUINORCOM\ ENVIRONMENT=${ARG_ENV}\ DT_PROCESS_GROUP=${ARG_SANITY_DATASET}
 
 EXPOSE "$PORT"
-CMD ["pnpm", "web", "start"]
+
+CMD ["node", "server.js"]
+
