:art: try to isolate web folder in dockerfile

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,61 +1,38 @@
-FROM node:18-alpine AS base
-ENV PNPM_HOME="/pnpm"
-ENV PATH="$PNPM_HOME:$PATH"
-ENV NODE_OPTIONS="--max_old_space_size=8192"
-RUN corepack enable
-RUN corepack prepare pnpm@8.5.1 --activate
-COPY . /app
+FROM node:20-alpine AS base
+COPY web/ /app
 WORKDIR /app
 
-# Install dependencies only when needed
+# 1. Install dependencies only when needed
 FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package.json pnpm-lock.yaml ./
-COPY web/package.json web/pnpm-lock.yaml web/
-COPY web/patches web/patches
-
+# Install dependencies based on the preferred package manager
+COPY package.json pnpm-lock.yaml* .npmrc* ./
 RUN \
-  if [ -f pnpm-lock.yaml ]; then pnpm m i --frozen-lockfile;\
+  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
   else echo "Lockfile not found." && exit 1; \
   fi
 
+
+# 2. Rebuild the source code only when needed
 FROM base AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
-COPY --from=deps /app/web/node_modules ./web/node_modules
 COPY . .
 
-ARG ARG_SANITY_DATASET
-ARG ARG_SANITY_API_TOKEN
-ARG ARG_SANITY_PROJECT_ID
-ARG ARG_ALGOLIA_APP_ID
-ARG ARG_ALGOLIA_SEARCH_API_KEY
-ARG ARG_ARCHIVE_CONTENT_LINK
-ARG ARG_FRIENDLY_CAPTCHA_SITEKEY
-ARG ARG_FRIENDLY_CAPTCHA_PUZZLE_ENDPOINT
+ENV NEXT_TELEMETRY_DISABLED=1
+RUN \
+  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-ENV NEXT_PUBLIC_SANITY_DATASET ${ARG_SANITY_DATASET}
-ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${ARG_SANITY_PROJECT_ID}
-ENV SANITY_API_TOKEN ${ARG_SANITY_API_TOKEN}
-ENV NEXT_PUBLIC_ALGOLIA_APP_ID ${ARG_ALGOLIA_APP_ID}
-ENV NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY ${ARG_ALGOLIA_SEARCH_API_KEY}
-ENV NEXT_PUBLIC_ARCHIVE_CONTENT_LINK ${ARG_ARCHIVE_CONTENT_LINK}
-ENV NEXT_PUBLIC_FRIENDLY_CAPTCHA_SITEKEY ${ARG_FRIENDLY_CAPTCHA_SITEKEY}
-ENV NEXT_PUBLIC_FRIENDLY_CAPTCHA_PUZZLE_ENDPOINT ${ARG_FRIENDLY_CAPTCHA_PUZZLE_ENDPOINT} 
-
-# https://nextjs.org/telemetry
-ENV NEXT_TELEMETRY_DISABLED 1
-
-RUN pnpm web build
-
-# Production image, copy all the files and run next
+# 3. Production image, copy all the files and run next
 FROM base AS runner
 WORKDIR /app
 
-ENV NODE_ENV production
+ENV NODE_ENV=production
 
 ARG ARG_ENV
 ARG ARG_SANITY_DATASET
@@ -77,22 +54,77 @@ ENV UID 12345
 # https://nextjs.org/telemetry
 ENV NEXT_TELEMETRY_DISABLED 1
 
+
 RUN addgroup -S "$USER"
 RUN adduser -S --uid "$UID" "$USER"
 RUN apk add --no-cache tini
 
-COPY --from=builder /app/web/public ./public
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown="$USER":"$USER" /app/web/.next/standalone .
-COPY --from=builder --chown="$USER":"$USER" /app/web/.next/static ./.next/static
+COPY --from=builder --chown="$USER":"$USER" /app/.next/standalone ./
+COPY --from=builder --chown="$USER":"$USER" /app/.next/static ./.next/static
 
 USER "$UID"
-
 ENV NEXT_MANUAL_SIG_HANDLE=true
 
 EXPOSE "$PORT"
 
 ENTRYPOINT ["/sbin/tini", "--"]
 
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
+#why dont we have : ENV HOSTNAME="0.0.0.0"
 CMD ["node", "server.js"]
 
+
+
+#-------TURBO DOCKER EX-------
+##FROM node:18-alpine AS base
+ 
+#FROM base AS builder
+#RUN apk update
+#RUN apk add --no-cache libc6-compat
+
+#WORKDIR /app
+#RUN yarn global add turbo@^<your-major-version>
+#COPY . .
+ 
+# Generate a partial monorepo with a pruned lockfile for a target workspace.
+# Assuming "web" is the name entered in the project's package.json: { name: "web" }
+#RUN turbo prune web --docker
+ 
+## Add lockfile and package.json's of isolated subworkspace
+#FROM base AS installer
+#RUN apk update
+#RUN apk add --no-cache libc6-compat
+#WORKDIR /app
+ 
+# First install the dependencies (as they change less often)
+#COPY --from=builder /app/out/json/ .
+#RUN yarn install --frozen-lockfile
+ 
+# Build the project
+#COPY --from=builder /app/out/full/ .
+#RUN yarn turbo run build
+ 
+#FROM base AS runner
+#WORKDIR /app
+ 
+# Don't run production as root
+#RUN addgroup --system --gid 1001 nodejs
+#RUN adduser --system --uid 1001 nextjs
+#USER nextjs
+ 
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+#COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
+#COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
+#COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
+ 
+#CMD node apps/web/server.js
+
+
+#-------TURBO DOCKER EX END-------
